# Generated by Django 4.2.7 on 2025-10-03 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente_id', models.PositiveIntegerField(help_text='ID del docente desde el servicio AUTH', validators=[django.core.validators.MinValueValidator(1)])),
                ('aula', models.CharField(help_text='Aula donde se dicta la clase', max_length=50)),
                ('seccion', models.CharField(help_text='Sección o grupo de estudiantes', max_length=50)),
                ('fecha', models.DateField(help_text='Fecha del registro de asistencia')),
                ('hora_entrada', models.TimeField(help_text='Hora de entrada registrada')),
                ('hora_salida', models.TimeField(blank=True, help_text='Hora de salida (opcional)', null=True)),
                ('estado', models.CharField(choices=[('PUNTUAL', 'Puntual'), ('TARDANZA', 'Tardanza'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado'), ('FALTA', 'Falta')], default='PUNTUAL', help_text='Estado de la asistencia', max_length=20)),
                ('observacion', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('minutos_tardanza', models.PositiveIntegerField(default=0, help_text='Minutos de tardanza calculados')),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento monetario aplicado por tardanza', max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'registro_asistencia',
                'ordering': ['-fecha', '-hora_entrada'],
                'indexes': [models.Index(fields=['docente_id'], name='idx_docente_id'), models.Index(fields=['fecha'], name='idx_fecha'), models.Index(fields=['estado'], name='idx_estado'), models.Index(fields=['fecha_creacion'], name='idx_fecha_creacion')],
                'unique_together': {('docente_id', 'fecha', 'seccion')},
            },
        ),
        migrations.CreateModel(
            name='JustificacionAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente_id', models.PositiveIntegerField(help_text='ID del docente desde el servicio AUTH', validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha', models.DateField(help_text='Fecha de la ausencia a justificar')),
                ('motivo', models.TextField(help_text='Motivo detallado de la ausencia')),
                ('tipo_motivo', models.CharField(choices=[('ENFERMEDAD', 'Enfermedad'), ('EMERGENCIA_FAMILIAR', 'Emergencia familiar'), ('PERMISO_PERSONAL', 'Permiso personal'), ('CAPACITACION', 'Capacitación'), ('OTROS', 'Otros')], default='OTROS', help_text='Categoría del motivo', max_length=50)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EN_REVISION', 'En revisión')], default='PENDIENTE', help_text='Estado de la justificación', max_length=20)),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Documento de respaldo (opcional)', null=True, upload_to='justificaciones/')),
                ('observaciones_revisor', models.TextField(blank=True, help_text='Observaciones del revisor')),
                ('fecha_revision', models.DateTimeField(blank=True, help_text='Fecha de revisión de la justificación', null=True)),
                ('revisor_id', models.PositiveIntegerField(blank=True, help_text='ID del usuario que revisó la justificación', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'justificacion_ausencia',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['docente_id'], name='idx_just_docente_id'), models.Index(fields=['fecha'], name='idx_just_fecha'), models.Index(fields=['estado'], name='idx_just_estado'), models.Index(fields=['fecha_creacion'], name='idx_just_fecha_creacion')],
            },
        ),
    ]
