# Generated by Django 4.2.7 on 2025-10-04 00:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(help_text='Nombre de la métrica', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la métrica')),
                ('tipo', models.CharField(choices=[('CONTADOR', 'Contador'), ('PORCENTAJE', 'Porcentaje'), ('PROMEDIO', 'Promedio'), ('SUMA', 'Suma'), ('MAXIMO', 'Máximo'), ('MINIMO', 'Mínimo'), ('RATIO', 'Ratio')], default='CONTADOR', help_text='Tipo de métrica', max_length=15)),
                ('valor', models.DecimalField(decimal_places=4, help_text='Valor numérico de la métrica', max_digits=15)),
                ('periodo', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('ANUAL', 'Anual'), ('PERSONALIZADO', 'Personalizado')], default='DIARIO', help_text='Período de la métrica', max_length=15)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del período')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin del período')),
                ('unidad', models.CharField(blank=True, help_text='Unidad de medida (ej: %, personas, soles)', max_length=50)),
                ('categoria', models.CharField(blank=True, help_text='Categoría de la métrica', max_length=100)),
                ('etiquetas', models.JSONField(default=dict, help_text='Etiquetas adicionales para filtrado')),
                ('fuente', models.CharField(blank=True, help_text='Fuente de datos de la métrica', max_length=100)),
                ('autor_calculo_id', models.CharField(blank=True, help_text='ID del usuario o sistema que calculó la métrica', max_length=50)),
                ('fecha_calculo', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del cálculo')),
                ('valor_objetivo', models.DecimalField(blank=True, decimal_places=4, help_text='Valor objetivo para la métrica', max_digits=15, null=True)),
                ('umbral_minimo', models.DecimalField(blank=True, decimal_places=4, help_text='Umbral mínimo para alertas', max_digits=15, null=True)),
                ('umbral_maximo', models.DecimalField(blank=True, decimal_places=4, help_text='Umbral máximo para alertas', max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del reporte', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del reporte')),
                ('tipo', models.CharField(choices=[('ASISTENCIA', 'Reporte de Asistencia'), ('PAGOS', 'Reporte de Pagos'), ('ESTUDIANTES', 'Reporte de Estudiantes'), ('METRICAS', 'Reporte de Métricas'), ('FINANCIERO', 'Reporte Financiero'), ('ACADEMICO', 'Reporte Académico'), ('ADMINISTRATIVO', 'Reporte Administrativo'), ('PERSONALIZADO', 'Reporte Personalizado')], default='PERSONALIZADO', help_text='Tipo de reporte', max_length=20)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('JSON', 'JSON')], default='PDF', help_text='Formato de exportación', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', help_text='Estado actual del reporte', max_length=15)),
                ('parametros', models.JSONField(default=dict, help_text='Parámetros de configuración del reporte')),
                ('autor_id', models.CharField(help_text='ID del usuario que solicitó el reporte', max_length=50)),
                ('autor_nombre', models.CharField(help_text='Nombre del usuario que solicitó el reporte', max_length=255)),
                ('autor_email', models.EmailField(blank=True, help_text='Email del usuario para notificaciones', max_length=254)),
                ('fecha_inicio_procesamiento', models.DateTimeField(blank=True, help_text='Fecha y hora de inicio del procesamiento', null=True)),
                ('fecha_fin_procesamiento', models.DateTimeField(blank=True, help_text='Fecha y hora de finalización del procesamiento', null=True)),
                ('archivo', models.FileField(blank=True, help_text='Archivo del reporte generado', null=True, upload_to='reportes/%Y/%m/')),
                ('archivo_nombre', models.CharField(blank=True, help_text='Nombre original del archivo', max_length=255)),
                ('archivo_tamaño', models.PositiveIntegerField(default=0, help_text='Tamaño del archivo en bytes')),
                ('tiempo_procesamiento', models.DurationField(blank=True, help_text='Tiempo total de procesamiento', null=True)),
                ('registros_procesados', models.PositiveIntegerField(default=0, help_text='Número de registros procesados')),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si el procesamiento falló')),
                ('notificar_por_email', models.BooleanField(default=True, help_text='Enviar notificación por email al completar')),
                ('publico', models.BooleanField(default=False, help_text='Reporte público (visible para otros usuarios)')),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha de expiración del reporte', null=True)),
                ('tags', models.JSONField(default=list, help_text='Etiquetas para categorizar el reporte')),
                ('version', models.PositiveIntegerField(default=1, help_text='Versión del reporte')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ReporteMetrica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('incluir_grafico', models.BooleanField(default=True, help_text='Incluir gráfico de esta métrica')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de la métrica en el reporte')),
                ('configuracion_grafico', models.JSONField(default=dict, help_text='Configuración específica del gráfico')),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_incluidos', to='reportes_app.metrica')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_incluidas', to='reportes_app.reporte')),
            ],
            options={
                'verbose_name': 'Reporte-Métrica',
                'verbose_name_plural': 'Reportes-Métricas',
                'ordering': ['orden', 'metrica__nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['tipo', 'estado'], name='reportes_ap_tipo_e8f892_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['autor_id'], name='reportes_ap_autor_i_660954_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['fecha_creacion'], name='reportes_ap_fecha_c_d6f9d1_idx'),
        ),
        migrations.AddIndex(
            model_name='metrica',
            index=models.Index(fields=['nombre', 'periodo'], name='reportes_ap_nombre_dfc787_idx'),
        ),
        migrations.AddIndex(
            model_name='metrica',
            index=models.Index(fields=['categoria'], name='reportes_ap_categor_1d1554_idx'),
        ),
        migrations.AddIndex(
            model_name='metrica',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='reportes_ap_fecha_i_f8fd96_idx'),
        ),
        migrations.AddIndex(
            model_name='metrica',
            index=models.Index(fields=['fecha_calculo'], name='reportes_ap_fecha_c_9cca8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metrica',
            unique_together={('nombre', 'periodo', 'fecha_inicio', 'fecha_fin')},
        ),
        migrations.AlterUniqueTogether(
            name='reportemetrica',
            unique_together={('reporte', 'metrica')},
        ),
    ]
