# Generated by Django 4.2.7 on 2025-10-03 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='usr_prof_cargo_idx',
        ),
        migrations.RenameIndex(
            model_name='profile',
            new_name='profiles_usuario_4acf71_idx',
            old_name='usr_prof_usuario_id_idx',
        ),
        migrations.RenameIndex(
            model_name='profile',
            new_name='profiles_departa_91ef50_idx',
            old_name='usr_prof_depto_idx',
        ),
        migrations.RenameIndex(
            model_name='profile',
            new_name='profiles_fecha_c_69a854_idx',
            old_name='usr_prof_fecha_crea_idx',
        ),
        migrations.RenameIndex(
            model_name='profile',
            new_name='profiles_activo_2d0183_idx',
            old_name='usr_prof_activo_idx',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='codigo_empleado',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contacto_emergencia_nombre',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contacto_emergencia_telefono',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='extension_telefonica',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='modificado_por',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='URL del avatar del usuario', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='biografia',
            field=models.TextField(blank=True, help_text='Biografía o descripción personal', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mostrar_correo',
            field=models.BooleanField(default=True, help_text='Mostrar correo en el perfil público'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mostrar_telefono',
            field=models.BooleanField(default=False, help_text='Mostrar teléfono en el perfil público'),
        ),
        migrations.AddField(
            model_name='profile',
            name='perfil_publico',
            field=models.BooleanField(default=True, help_text='Indica si el perfil es visible públicamente'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cargo',
            field=models.CharField(blank=True, help_text='Cargo o posición del usuario', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='departamento',
            field=models.CharField(blank=True, help_text='Departamento o área de trabajo/estudio', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='direccion',
            field=models.TextField(blank=True, help_text='Dirección de residencia del usuario', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono del usuario', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Número de teléfono debe tener el formato: +999999999. Máximo 15 dígitos.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='usuario_id',
            field=models.PositiveIntegerField(help_text='ID del usuario en el servicio de autenticación', unique=True),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
    ]
