# Generated by Django 4.2.7 on 2025-10-04 01:08

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadSistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la actividad', primary_key=True, serialize=False)),
                ('usuario_id', models.IntegerField(blank=True, help_text='ID del usuario que realizó la acción (null para usuarios anónimos)', null=True)),
                ('usuario_email', models.EmailField(blank=True, help_text='Email del usuario para facilitar búsquedas', max_length=255, null=True)),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('LOGIN_FAILED', 'Intento de Login Fallido'), ('CREATE', 'Crear'), ('READ', 'Leer/Consultar'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('UPLOAD', 'Cargar Archivo'), ('DOWNLOAD', 'Descargar Archivo'), ('EXPORT', 'Exportar Datos'), ('IMPORT', 'Importar Datos'), ('STATUS_CHANGE', 'Cambio de Estado'), ('APPROVE', 'Aprobar'), ('REJECT', 'Rechazar'), ('ERROR', 'Error del Sistema'), ('WARNING', 'Advertencia'), ('EXCEPTION', 'Excepción'), ('ACCESS_GRANTED', 'Acceso Concedido'), ('ACCESS_DENIED', 'Acceso Denegado'), ('OTHER', 'Otra Acción')], help_text='Tipo de acción realizada', max_length=50)),
                ('recurso', models.CharField(choices=[('AUTH', 'Autenticación'), ('USERS', 'Usuarios'), ('DOCUMENTS', 'Documentos'), ('PAYMENTS', 'Pagos'), ('ATTENDANCE', 'Asistencia'), ('REPORTS', 'Reportes'), ('AUDIT', 'Auditoría'), ('USER_PROFILE', 'Perfil de Usuario'), ('DOCUMENT_FILE', 'Archivo de Documento'), ('PAYMENT_TRANSACTION', 'Transacción de Pago'), ('ATTENDANCE_RECORD', 'Registro de Asistencia'), ('REPORT_GENERATION', 'Generación de Reporte'), ('SYSTEM', 'Sistema'), ('DATABASE', 'Base de Datos'), ('API', 'API'), ('MIDDLEWARE', 'Middleware'), ('OTHER', 'Otro Recurso')], help_text='Recurso afectado por la acción', max_length=100)),
                ('recurso_id', models.CharField(blank=True, help_text='ID específico del recurso afectado', max_length=100, null=True)),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Fecha y hora de la actividad')),
                ('detalle', models.JSONField(default=dict, help_text='Detalles adicionales de la actividad en formato JSON')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent del navegador o cliente', null=True)),
                ('session_key', models.CharField(blank=True, help_text='Clave de sesión para agrupar actividades', max_length=100, null=True)),
                ('metodo_http', models.CharField(blank=True, help_text='Método HTTP utilizado (GET, POST, etc.)', max_length=10, null=True)),
                ('url_solicitada', models.URLField(blank=True, help_text='URL que fue solicitada', max_length=500, null=True)),
                ('codigo_estado', models.IntegerField(blank=True, help_text='Código de estado HTTP de la respuesta', null=True)),
                ('nivel_criticidad', models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto'), ('CRITICAL', 'Crítico')], default='LOW', help_text='Nivel de criticidad de la actividad', max_length=20)),
                ('duracion_ms', models.IntegerField(blank=True, help_text='Duración de la operación en milisegundos', null=True)),
                ('exito', models.BooleanField(default=True, help_text='Indica si la operación fue exitosa')),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si la operación falló', null=True)),
                ('microservicio', models.CharField(default='AUDIT', help_text='Microservicio que generó el log', max_length=50)),
                ('version_api', models.CharField(blank=True, help_text='Versión de la API utilizada', max_length=20, null=True)),
                ('tags', models.JSONField(default=list, help_text='Tags para categorizar y filtrar actividades')),
            ],
            options={
                'verbose_name': 'Actividad del Sistema',
                'verbose_name_plural': 'Actividades del Sistema',
                'db_table': 'auditoria_actividad_sistema',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='auditoria_a_fecha_441fce_idx'), models.Index(fields=['usuario_id'], name='auditoria_a_usuario_83e0ea_idx'), models.Index(fields=['accion'], name='auditoria_a_accion_f35d4e_idx'), models.Index(fields=['recurso'], name='auditoria_a_recurso_a1e393_idx'), models.Index(fields=['nivel_criticidad'], name='auditoria_a_nivel_c_a9d79a_idx'), models.Index(fields=['exito'], name='auditoria_a_exito_934c34_idx'), models.Index(fields=['microservicio'], name='auditoria_a_microse_2ed2f2_idx'), models.Index(fields=['fecha', 'usuario_id'], name='auditoria_a_fecha_1bb703_idx'), models.Index(fields=['accion', 'recurso'], name='auditoria_a_accion_076c90_idx')],
            },
        ),
    ]
