# Generated by Django 4.2.7 on 2025-10-04 00:35

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ASIG_FAM', 'Asignación Familiar'), ('PRODUCTIVIDAD', 'Bono Productividad'), ('HORAS_EXTRAS', 'Horas Extras'), ('GRATIFICACION', 'Gratificación'), ('CTS', 'CTS'), ('VACACIONES', 'Vacaciones'), ('OTROS', 'Otros')], max_length=20)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('monto_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.TextField(blank=True)),
                ('requiere_aprobacion', models.BooleanField(default=False)),
                ('aplicable_desde', models.DateField(default=datetime.date.today)),
                ('aplicable_hasta', models.DateField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bonificación',
                'verbose_name_plural': 'Bonificaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ESSALUD', 'EsSalud (9%)'), ('ONP', 'ONP (13%)'), ('AFP', 'AFP'), ('QUINTA', 'Quinta Categoría'), ('PRESTAMO', 'Préstamo'), ('ADELANTO', 'Adelanto'), ('OTROS', 'Otros')], max_length=20)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('monto_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.TextField(blank=True)),
                ('obligatorio', models.BooleanField(default=False)),
                ('aplicable_desde', models.DateField(default=datetime.date.today)),
                ('aplicable_hasta', models.DateField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('trabajador_id', models.CharField(db_index=True, max_length=20)),
                ('trabajador_nombre', models.CharField(max_length=200)),
                ('trabajador_documento', models.CharField(max_length=20)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_bonificaciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('CALCULADO', 'Calculado'), ('APROBADO', 'Aprobado'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='CALCULADO', max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('dias_trabajados', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_bonificaciones', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cantidad_trabajadores', models.IntegerField(default=0)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('procesada', models.BooleanField(default=False)),
                ('aprobada', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planilla',
                'verbose_name_plural': 'Planillas',
                'ordering': ['-año', '-mes'],
                'unique_together': {('año', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='PagoDescuento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('monto_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_personalizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos_app.descuento')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos_app.pago')),
            ],
            options={
                'verbose_name': 'Descuento de Pago',
                'verbose_name_plural': 'Descuentos de Pago',
                'unique_together': {('pago', 'descuento')},
            },
        ),
        migrations.CreateModel(
            name='PagoBonificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('monto_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_personalizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('bonificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos_app.bonificacion')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos_app.pago')),
            ],
            options={
                'verbose_name': 'Bonificación de Pago',
                'verbose_name_plural': 'Bonificaciones de Pago',
                'unique_together': {('pago', 'bonificacion')},
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='bonificaciones_aplicadas',
            field=models.ManyToManyField(blank=True, through='pagos_app.PagoBonificacion', to='pagos_app.bonificacion'),
        ),
        migrations.AddField(
            model_name='pago',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='descuentos_aplicados',
            field=models.ManyToManyField(blank=True, through='pagos_app.PagoDescuento', to='pagos_app.descuento'),
        ),
        migrations.AddField(
            model_name='pago',
            name='planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pagos_app.planilla'),
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('numero_boleta', models.CharField(db_index=True, max_length=50, unique=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='boletas/%Y/%m/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('tamaño_archivo', models.IntegerField(blank=True, null=True)),
                ('hash_archivo', models.CharField(blank=True, max_length=64, null=True)),
                ('version', models.IntegerField(default=1)),
                ('enviada_por_email', models.BooleanField(default=False)),
                ('fecha_envio_email', models.DateTimeField(blank=True, null=True)),
                ('boleta_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_posteriores', to='pagos_app.boleta')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('generada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletas_generadas', to=settings.AUTH_USER_MODEL)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleta', to='pagos_app.pago')),
            ],
            options={
                'verbose_name': 'Boleta de Pago',
                'verbose_name_plural': 'Boletas de Pago',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='Adelanto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('trabajador_id', models.CharField(db_index=True, max_length=20)),
                ('trabajador_nombre', models.CharField(max_length=200)),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_aprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_descuento', models.DateField(blank=True, help_text='Fecha en que se descontará del sueldo', null=True)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('DESCONTADO', 'Descontado'), ('RECHAZADO', 'Rechazado')], default='SOLICITADO', max_length=20)),
                ('motivo', models.TextField()),
                ('observaciones_aprobacion', models.TextField(blank=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adelantos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pago_descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adelantos_descontados', to='pagos_app.pago')),
            ],
            options={
                'verbose_name': 'Adelanto',
                'verbose_name_plural': 'Adelantos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='pago',
            unique_together={('planilla', 'trabajador_id')},
        ),
    ]
